var a = 10;
document.write("Result:");
document.write("<br/>The value of a is "+a);
document.write("<br/>.............................................");
//++a;
document.write("<br/><br/>The value of ++a is "+ ++a);
document.write("<br/>Now the value of a is "+ a);
document.write("<br/><br/>The value of a++ is "+a++);
document.write("<br/>Now the value of a is "+ a);
document.write("<br/><br/>The value of --a is "+ --a);
document.write("<br/>Now the value of a is "+ a);
document.write("<br/><br/>The value of a-- is "+a--);
document.write("<br/>Now the value of a is "+ a);
document.write('<br/><br/><b><hr size="2", color="black"></b>');